// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $button from "./routes/button.tsx";
import * as $characters from "./routes/characters.tsx";
import * as $characters_id_ from "./routes/characters/[id].tsx";
import * as $greet from "./routes/greet.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $saludar from "./routes/saludar.tsx";
import * as $test_layout from "./routes/test/_layout.tsx";
import * as $test_page1 from "./routes/test/page1.tsx";
import * as $test_page2 from "./routes/test/page2.tsx";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/joke.ts": $api_joke,
    "./routes/button.tsx": $button,
    "./routes/characters.tsx": $characters,
    "./routes/characters/[id].tsx": $characters_id_,
    "./routes/greet.tsx": $greet,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/saludar.tsx": $saludar,
    "./routes/test/_layout.tsx": $test_layout,
    "./routes/test/page1.tsx": $test_page1,
    "./routes/test/page2.tsx": $test_page2,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
