// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $Rick_Morty_characters from "./routes/Rick&Morty/characters.tsx";
import * as $Rick_Morty_characters_id_ from "./routes/Rick&Morty/characters/[id].tsx";
import * as $Rick_Morty_episode_id_ from "./routes/Rick&Morty/episode/[id].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $button from "./routes/button.tsx";
import * as $client_ricky from "./routes/client-ricky.tsx";
import * as $contacts from "./routes/contacts.tsx";
import * as $form from "./routes/form.tsx";
import * as $greet from "./routes/greet.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $saludar from "./routes/saludar.tsx";
import * as $signals_ricky from "./routes/signals-ricky.tsx";
import * as $signals from "./routes/signals.tsx";
import * as $test_layout from "./routes/test/_layout.tsx";
import * as $test_page1 from "./routes/test/page1.tsx";
import * as $test_page2 from "./routes/test/page2.tsx";
import * as $Formulario from "./islands/Formulario.tsx";
import * as $RickyList from "./islands/RickyList.tsx";
import * as $Signals_ricky_Buscador from "./islands/Signals-ricky/Buscador.tsx";
import * as $Signals_ricky_Paginador from "./islands/Signals-ricky/Paginador.tsx";
import * as $Signals_ricky_Resultados from "./islands/Signals-ricky/Resultados.tsx";
import * as $Signals_SignalIslandOne from "./islands/Signals/SignalIslandOne.tsx";
import * as $Signals_SignalIslandTwo from "./islands/Signals/SignalIslandTwo.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/Rick&Morty/characters.tsx": $Rick_Morty_characters,
    "./routes/Rick&Morty/characters/[id].tsx": $Rick_Morty_characters_id_,
    "./routes/Rick&Morty/episode/[id].tsx": $Rick_Morty_episode_id_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/button.tsx": $button,
    "./routes/client-ricky.tsx": $client_ricky,
    "./routes/contacts.tsx": $contacts,
    "./routes/form.tsx": $form,
    "./routes/greet.tsx": $greet,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/saludar.tsx": $saludar,
    "./routes/signals-ricky.tsx": $signals_ricky,
    "./routes/signals.tsx": $signals,
    "./routes/test/_layout.tsx": $test_layout,
    "./routes/test/page1.tsx": $test_page1,
    "./routes/test/page2.tsx": $test_page2,
  },
  islands: {
    "./islands/Formulario.tsx": $Formulario,
    "./islands/RickyList.tsx": $RickyList,
    "./islands/Signals-ricky/Buscador.tsx": $Signals_ricky_Buscador,
    "./islands/Signals-ricky/Paginador.tsx": $Signals_ricky_Paginador,
    "./islands/Signals-ricky/Resultados.tsx": $Signals_ricky_Resultados,
    "./islands/Signals/SignalIslandOne.tsx": $Signals_SignalIslandOne,
    "./islands/Signals/SignalIslandTwo.tsx": $Signals_SignalIslandTwo,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
